2025-08-16 00:02:39,631 - INFO - Log file for this run: logs\generation_20250816_000239.log
2025-08-16 00:02:39,632 - INFO - --- Starting OLTP Database Generation ---
2025-08-16 00:02:39,632 - INFO - Reproducible Seed: 36
2025-08-16 00:02:39,633 - ERROR - A fatal error occurred during script execution.
Traceback (most recent call last):
  File "C:\Users\liiri\Documents\Projects\py_project\ProjectBank\generate_dataset.py", line 467, in <module>
    households_list = generate_households(config)
  File "C:\Users\liiri\Documents\Projects\py_project\ProjectBank\generate_dataset.py", line 113, in generate_households
    "last_name": fake.last_name(),
                 ^^^^
NameError: name 'fake' is not defined. Did you mean: 'Faker'?
